name: "Publish New Draft Version"
on:
  push:
    tags:
      - "draft-*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Draft tag to publish (e.g. draft-foo-bar-00)"
        required: true
        type: string
      email:
        description: "Submitter email"
        default: ""
        type: string
jobs:
  build:
    name: "Publish New Draft Version"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true
    # See https://github.com/actions/checkout/issues/290
    - name: "Get Tag Annotations"
      if: startsWith(github.ref, 'refs/tags/')
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}
    - name: "Checkout Tag for Manual Run"
      if: github.event_name == 'workflow_dispatch'
      run: |
        git fetch -f origin refs/tags/${{ inputs.tag }}:refs/tags/${{ inputs.tag }}
        git checkout refs/tags/${{ inputs.tag }}
    - name: "Setup"
      id: setup
      run: date -u "+date=%FT%T" >>"$GITHUB_OUTPUT"
    - name: "Caching"
      uses: actions/cache@v4
      with:
        path: |
          .refcache
          .venv
          .gems
          node_modules
          .targets.mk
        key: i-d-${{ steps.setup.outputs.date }}
        restore-keys: i-d-
    - name: "Build Drafts"
      id: build
      uses: martinthomson/i-d-template@v1
      with:
        make: releases
        token: ${{ github.token }}
    - name: "Upload to Datatracker"
      uses: martinthomson/i-d-template@v1
      with:
        make: upload
      env:
        UPLOAD_EMAIL: ${{ inputs.email }}
        GITHUB_STEP: upload
    - name: "Archive Submitted Drafts"
      uses: actions/upload-artifact@v4
      if: always() && steps.build.outcome == 'success'
      with:
        name: published
        path: "versioned/draft-*-[0-9][0-9].*"
